config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get '/home/about', to: 'homes#about'
  devise_for :users
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :book_own, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_own
    if current_user != Book.find(params[:id]).user
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
    flash[:notice] = "Welcome! You have signed up successfully."
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    flash[:notice] = "Signed out successfully."
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_own, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_own
    if current_user != User.find(params[:id])
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_create.html.erb
<h2>New book</h2>
<!--エラーメッセージ-->
<% if book.errors.any? %>
  <h3 id="error_message"><%= book.errors.count %>件のerrorが発生しました</h3>
  <% book.errors.full_messages.each do |message| %><br>
    <p id="error_message"><span>・</span><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: book, local:true do |f| %>
    <div class="form-group">
      <%= f.label :title %><br />
      <%= f.text_field :title, class:"form-control" %>
    </div>
  <div class="form-group">
    <%= f.label :opinion %><br />
    <%= f.text_area :body, class:"form-control", rows:"2" %>
  </div>
  <br>
  <%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>

app/views/books/_list.html.erb
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</td>
      <th>Opinion</td>
    </tr>
  </thead>
  <tbody>
      <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>
            <% end %>
          </td>
          <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
  </tbody>
</table>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-8 px-5">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3 id="error_message"><%= @book.errors.count %>件のerrorが発生しました</h3>
        <% @book.errors.full_messages.each do |message| %><br>
          <p id="error_message"><span>・</span><%= message %></p>
        <% end %>
      <% end %>

      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="title">Title</label><br>
          <%= f.text_field :title, autofocus: true, id:"title", class:"form-control" %><br>
        </div>
        <div class="form-group">
          <label for="body">Opinion</label><br>
          <%= f.text_area :body, autofocus: true, id:"body", class:"form-control"%><br>
        </div>
        <%= f.submit "Update Book", class: "btn btn-success mb-3" %><br>

        <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/create', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'books/list', books: @books %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'books/create', book: @book %>

app/views/books/show.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div id="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/create', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td align="center">
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td align="center">
              <%= link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td align="center"><%= @book.body %></td>
            <td align="center">
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
              <% end %>
            </td>
            <td align="center">
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="mx-auto px-3">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div id="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
    <div class="row">
      <div class="mx-auto">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>in<strong>Bookers</strong><i class="fas fa-book"></i></p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="col-10 mx-auto">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-block btn-sm btn-info mb-3" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-block btn-sm btn-success" %>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-2 text-white" href="/"><%= "Bookers2" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                  <i class="fas fa-home"></i><span> Home</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-users"></i><span> Users</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-book-open"></i><span> Books</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                  <i class="fas fa-sign-out-alt"></i><span> logout</span>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-home"></i><span> Home</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to home_about_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-link"></i><span> About</span>
                <% end%>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-user-plus"></i><span> sign up</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-sign-in-alt"></i><span> login</span>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
  <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
</html>

app/views/users/_info.html.erb
<h2>User Info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">
  <tr>
    <td align="center" nowrap>name</td>
    <td valign="top"><%= user.name %></td>
  </tr>
  <tr>
    <td align="center" nowrap>introduction</td>
    <td valign="top"><%= user.introduction %></td>
  </tr>
</table>
    <%= link_to edit_user_path(user), class: "btn btn-block btn-sm btn-outline-secondary mt-5 mb-3" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h2>User Info</h2>
      <% if @user.errors.any? %>
        <h3 id="error_message"><%= @user.errors.count %>件のerrorが発生しました</h3>
        <% @user.errors.full_messages.each do |message| %><br>
          <p id="error_message"><span>・</span><%= message %></p>
        <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="name">Name</label><br>
          <%= f.text_field :name, autofocus: true, id:"name", class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="image">Image</label><br>
          <%= f.attachment_field :profile_image %>
        </div>

        <div class="form-group">
          <label for="introduction">Introduction</label><br>
          <%= f.text_field :introduction, autofocus: true, id:"introduction", class:"form-control" %>
        </div>

        <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/create', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</td>
            <th>name</td>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div id="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/create', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'books/list', books: @books %>
    </div>
  </div>
</div>